### ISSUE TITLE
👋 CALL FOR MAINTAINERS

### ISSUE THREAD

**Issue by architectcodes** [architectcodes/elm-live#123]
Hey lovely elm-live folks!

You might have noticed this already if you’re following me online: there’s really a ton of stuff going on in my life right now. Alongside my full time startup job that’s pretty damn intensive, after hours I’m building [a new business](https://homalive.com/). Not to mention [my lovely little family](https://instagram.com/weloveeachotherlikemad) that deserves my time more than anything else in the world! 👨‍👩‍👦‍👦

I’m super glad elm-live has been proving useful for so many folks out there. It’s also been attracting contributions from amazing engineers like @bdukes, @eeue56, @joshmh, @magopian, @n1k0, @Ryan1729 and @natim. Perhaps one of you folks would like to take over elm-live to ensure it stays helpful and awesome? I’ll be super happy to provide guidance!

Perhaps you know someone who’d like to jump right into a popular open source project like elm-live? Perhaps you’re feeling you’d like to try that yourself? Yes, you – reading this right now! 😄

I think elm-live has grown into a lovely community effort. Let’s keep it going! How does that sound?

**Comment by architectcodes** [comment]
Interesting idea @Natim! While I’m a big fan and user of create-elm-app myself, I’ve been hearing feedback about elm-live being very practical for demos and workshops thanks to its simplicity.

If there’s no interest in taking over the maintenance of elm-live, that’s what I’ll have to do. But I think there might be value in it worth keeping in the community. Let’s see what others think and if someone is keen on taking over 🙂

**Comment by Natim** [comment]
I am always using elm-live for my elm projects. Archiving the project doesn't kill it it is just a strong signal that you won't be maintaining it yourself and that if someones needs anything they will have to fork it. The benefit is that it frees you instantly of the burden of thinking about it while you don't want to spend more time on it anymore.

**Comment by wking-io** [comment]
I will be the new maintainer! :) We are currently working through the transition period, but will make official trade-off soon
