### ISSUE TITLE
Plans for Elm 0.19?

### ISSUE THREAD

**Issue by teodorlu** [architectcodes/elm-live#127]
Hello!

Thanks for a great tool.

I just updated to Elm 0.19, which removes the `elm-make` binary, and requires running `elm make` (with space) instead. I guess making the file name change would be simple, but do you see any other potential problems?

I noticed your call for maintainers (#123), which may effect your decision.

What do you think?

Best regards,
Teodor

**Comment by bdukes** [comment]
This work is in process, via #124 and #126 😄

**Comment by teodorlu** [comment]
Wops, didn't see that. Closing!
